export const red = '✎red'
export const green = '✎green'
export const yellow = '✎yellow'
export const blue = '✎blue'
export const magenta = '✎magenta'
export const cyan = '✎cyan'
export const white = '✎white'
